version: "3"

services:
  ibmmq:
    build:
      context: mq-with-ssl/
      args:
        - http_proxy
    volumes:
      - mq_java_lib:/opt/mqm/java/lib
      - mq_certs:/etc/mqcerts
    ports:
      - "1414:1414"
      - "9443:9443"

  mqclient:
    build: mqclient_with_ssl/
    links:
      - ibmmq
    volumes:
      - mq_java_lib:/opt/mqm/java/lib
      - mq_certs:/etc/mqcerts

#  mqclientnossl:
#    build: mqclient_no_ssl/
#    links:
#      - ibmmq
#    volumes:
#      - mq_java_lib:/opt/mqm/java/lib
#      - mq_certs:/etc/mqcerts

volumes:
  mq_java_lib:
  mq_certs: