version: "3"

services:
  ibmmq:
    build: mq-with-ssl/
    volumes:
      - mq_java_lib:/opt/mqm/java/lib
    ports:
      - "1414:1414"
      - "9443:9443"

  mqclient:
    build: .
    links:
      - ibmmq
    volumes:
      - mq_java_lib:/opt/mqm/java/lib

volumes:
  mq_java_lib: